### PR TITLE
Label modern theme

### PR DESCRIPTION
**Pull request by Blackbaud-PaulCrowder**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-indicators?_sp.spa=pr-label-modern-theme](https://developer.blackbaud.com/skyux-indicators?_sp.spa=pr-label-modern-theme)

**Review by Blackbaud-AlexKingman — COMMENTED** [review]
In modern theme, the exclamation icons are slightly low and to the left. I'm wondering if we might need to update the styles there to something like...
```
&.sky-i-exclamation:before {
    position: relative;
    top: 1px;
    left: 0;
}
```

**Comment by Blackbaud-PaulCrowder** [comment]
> In modern theme, the exclamation icons are slightly low and to the left. I'm wondering if we might need to update the styles there to something like...
> 
> ```
> &.sky-i-exclamation:before {
>     position: relative;
>     top: 1px;
>     left: 0;
> }
> ```

This is because the icon glyphs are slightly disproportionate. Design is aware of this and will be making a second pass at the icons at some point.

**Review by Blackbaud-SteveBrush — APPROVED** [review]
LGTM

**Comment by Blackbaud-PaulCrowder** [comment]
#69

**Pull request merged**
